from sqlalchemy import Column, String, Integer, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class StudyViewTab(Base):
    __tablename__ = 'V_STUDYTAB'
    STUDYKEY = Column(Integer, primary_key=True)
    PID = Column(String)
    PNAME = Column(String)
    MODALITY = Column(String)
    STUDYDESC = Column(String)
    STUDYDATE = Column(String)
    REPORTSTATUS = Column(String)
    SERIESCNT = Column(Integer)
    IMAGECNT = Column(Integer)
    EXAMSTATUS = Column(String)

class User(Base):
    __tablename__ = 'V_USER'

    ID = Column(Text, primary_key=True)
    PASSWORD = Column(Text)

class SeriesTab(Base):
    __tablename__ = 'V_SERIESTAB'

    STUDYKEY = Column(Integer, primary_key=True)
    SERIESKEY = Column(Integer, primary_key=True)
    SERIESDESC = Column(Text)
    IMAGECNT = Column(Integer)
    PATH = Column(Text)
    FNAME = Column(Text)


class ImageViewTab(Base):
    __tablename__ = 'V_IMAGETAB'

    STUDYKEY = Column(Integer, primary_key=True)
    SERIESKEY = Column(Integer, primary_key=True)
    IMAGEKEY = Column(Integer)
    PATH = Column(Text)
    FNAME = Column(Text)

class StudyTab(Base):
    __tablename__ = 'studytab'

    STUDYKEY = Column(Integer, primary_key=True)
    STUDYINSUID = Column(Text)
    PATKEY = Column(Text)
    ACCESSNUM = Column(Text)
    STUDYDATE = Column(Integer)
    STUDYTIME = Column(Integer)
    STUDYID = Column(Text)
    EXAMCODE = Column(Text)
    STUDYDESC = Column(Text)
    MODALITY = Column(Text)
    BODYPART = Column(Text)
    PATIENTKEY = Column(Integer)
    PID = Column(Text)
    PNAME = Column(Text)
    PLASTNAME = Column(Text)
    PFIRSTNAME = Column(Text)
    PKNAME = Column(Text)
    PENAME = Column(Text)
    PSEX = Column(Text)
    PBIRTHDATETIME = Column(Integer)
    PATAGE = Column(Text)
    EXAMSTATUS = Column(Integer)
    REPORTSTATUS = Column(Integer)
    SERIESCNT = Column(Integer)
    SERIESMOVIECNT = Column(Text)
    IMAGECNT = Column(Integer)
    MOVIECNT = Column(Text)
    NONSERIESCOUNT = Column(Integer)
    NONIMAGECOUNT = Column(Integer)
    VERIFYFLAG = Column(Integer)
    VERIFYDATETIME = Column(Text)
    DEPT = Column(Text)
    REFPHYSICIANNAME = Column(Text)
    REQPHYSICIANNAME = Column(Text)
    PERFPHYSICIANNAME = Column(Text)
    OPERATORSNAME = Column(Text)
    REFERTODRID = Column(Text)
    REFERTODRNAME = Column(Text)
    PATKIND = Column(Text)
    WARD = Column(Text)
    SICKNAME = Column(Text)
    ADDEDINFO = Column(Text)
    HISCOMMENTS = Column(Text)
    HISADDEDINFO1 = Column(Text)
    HISADDEDINFO2 = Column(Text)
    HISADDEDINFO3 = Column(Text)
    INSNAME = Column(Text)
    STATIONNAME = Column(Text)
    CONFIRMDATETIME = Column(Text)
    READINGDATETIME = Column(Text)
    TRANSCRIBEDDATETIME = Column(Text)
    READTYPE = Column(Text)
    READCODE = Column(Text)
    READCODEDESC = Column(Text)
    READINGDR = Column(Text)
    CONFIRMDR = Column(Text)
    TRANSCRIPTIONIST = Column(Text)
    READINGKEYWORD = Column(Text)
    TEACHINGCASED = Column(Text)
    STEREOCOUNT = Column(Integer)
    PROTOCOLNAME = Column(Text)
    VIEWPOSITION = Column(Text)
    LATERALITY = Column(Text)
    REASON4STUDY = Column(Text)
    COMMENTS = Column(Text)
    STUDYTYPE = Column(Text)
    ARCHSTATUS = Column(Integer)
    COMPSTATUS = Column(Text)
    DELFLAG = Column(Integer)
    BACKUPSTATUS = Column(Integer)
    BACKUPLABEL = Column(Text)
    BACKUPDATETIME = Column(Text)
    MISMATCHFLAG = Column(Integer)
    READINGPRIORITY = Column(Integer)
    ABNORMALPATIENT = Column(Integer)
    INSERTDATE = Column(Integer)
    INSERTTIME = Column(Integer)
    HOSPITALID = Column(Integer)
    BURNCNT = Column(Integer)
    BURNDATETIME = Column(Text)
    VALIDATEFLAG = Column(Integer)
    REQREADSTATUS = Column(Integer)
    TBFLAG = Column(Integer)
    MOVIEFLAG = Column(Integer)
    OTHERSCPSENDSTATUS = Column(Integer)
    STATIONFILMROOM = Column(Text)
    RESERVED1 = Column(Text)
    RESERVED2 = Column(Text)
    RESERVED3 = Column(Text)
    RESERVED4 = Column(Text)
    RESERVED5 = Column(Text)
    RESERVED6 = Column(Text)
    RESERVED7 = Column(Text)
    RESERVED8 = Column(Text)
    RESERVED9 = Column(Text)
    RESERVED10 = Column(Text)
    AETITLE = Column(Text)
    OPENSTATUS = Column(Text)
    DAP = Column(Text)
    FILESIZE = Column(Integer)
    INSERTED = Column(Integer)
    UPDATED = Column(Integer)
    REMOTE_FLAG = Column(Text)
    AI_COMPANY = Column(Text)
    AI_MODEL_NAME = Column(Text)
    AI_UPDATED = Column(Text)
    AI_SCORE = Column(Text)
    AI_PRIORITY = Column(Text)
    AI_NUMBER_OF_FINDINGS = Column(Text)
    AI_ABNORMAL_YN = Column(Text)
    AI_FINDING = Column(Text)
    AI_REPORT = Column(Text)
    AI_VERSION = Column(Text)
    AI_RESULT_CODE = Column(Text)
    ACCESS_NUM = Column(Text)
    ADDED_INFO = Column(Text)
    AE_TITLE = Column(Text)
    BACKUP_DATE_TIME = Column(Text)
    BACKUP_LABEL = Column(Text)
    BODY_PART = Column(Text)
    BURN_DATE_TIME = Column(Text)
    CONFIRM_DATE_TIME = Column(Text)
    CONFIRM_DR = Column(Text)
    EXAM_CODE = Column(Text)
    HIS_ADDED_INFO1 = Column(Text)
    HIS_ADDED_INFO2 = Column(Text)
    HIS_ADDED_INFO3 = Column(Text)
    HIS_COMMENTS = Column(Text)
    INS_NAME = Column(Text)
    INSERT_DATE = Column(Text)
    INSERT_TIME = Column(Text)
    OPERATORS_NAME = Column(Text)
    PAT_AGE = Column(Text)
    PAT_KEY = Column(Text)
    PBIRTH_DATE_TIME = Column(Text)
    PERF_PHYSICIAN_NAME = Column(Text)
    PFIRST_NAME = Column(Text)
    PK_NAME = Column(Text)
    PLAST_NAME = Column(Text)
    PROTOCOL_NAME = Column(Text)
    READ_CODE = Column(Text)
    READ_CODE_DESC = Column(Text)
    READING_DATE_TIME = Column(Text)
    READING_DR = Column(Text)
    READING_KEYWORD = Column(Text)
    REASON_FOR_STUDY = Column(Text)
    REF_PHYSICIAN_NAME = Column(Text)
    REFER_TO_DR_NAME = Column(Text)
    REFER_TO_DRID = Column(Text)
    REQ_PHYSICIAN_NAME = Column(Text)
    SICK_NAME = Column(Text)
    STATION_FILM_ROOM = Column(Text)
    STATION_NAME = Column(Text)
    STUDY_DATE = Column(Text)
    STUDY_DESC = Column(Text)
    STUDY_ID = Column(Text)
    STUDY_INS_UID = Column(Text)
    STUDY_TIME = Column(Text)
    STUDY_TYPE = Column(Text)
    TRANSCRIBED_DATE_TIME = Column(Text)
    VERIFY_DATE_TIME = Column(Text)
    VIEW_POSITION = Column(Text)
    ABNORMAL_PATIENT = Column(Text)
    ARCH_STATUS = Column(Text)
    BACKUP_STATUS = Column(Text)
    BURN_CNT = Column(Text)
    COMP_STATUS = Column(Text)
    DEL_FLAG = Column(Text)
    EXAM_STATUS = Column(Text)
    FILE_SIZE = Column(Text)
    HOSPITAL_ID = Column(Text)
    IMAGE_CNT = Column(Text)
    MISMATCH_FLAG = Column(Text)
    MOVIE_CNT = Column(Text)
    MOVIE_FLAG = Column(Text)
    NON_IMAGE_COUNT = Column(Text)
    NON_SERIES_COUNT = Column(Text)
    OPEN_STATUS = Column(Text)
    OTHER_SCP_SEND_STATUS = Column(Integer)




class PatientTab(Base):
    __tablename__ = 'PATIENTTAB'

    PID = Column(String(64), primary_key=True)
    PNAME = Column(String(64), nullable=False)
    PATKEY = Column(String(64))
    PATIENTKEY = Column(Integer)
    PLASTNAME = Column(String(64))
    PFIRSTNAME = Column(String(64))
    PSEX = Column(String(2))
    PBIRTHDATE = Column(String(8))
    PBIRTHTIME = Column(String(8))
    COMMENTS = Column(String(64))
    INSERTDATE = Column(String(8))
    INSERTTIME = Column(String(8))
    HOSPITALID = Column(Integer, default=0)
    PKNAME = Column(String(64))
    PENAME = Column(String(64))
    INSNAME = Column(String(255))
    DELFLAG = Column(Integer)
    INSERTED = Column(String(14))
    UPDATED = Column(String(14))
    RESERVED1 = Column(Integer)
    RESERVED2 = Column(Integer)
    RESERVED3 = Column(Integer)
    RESERVED4 = Column(String(255))
    RESERVED5 = Column(String(255))
    RESERVED6 = Column(String(255))
    RESERVED7 = Column(String(255))
    RESERVED8 = Column(String(255))
    RESERVED9 = Column(String(255))
    RESERVED10 = Column(String(255))